import jsPDF from 'jspdf'

export interface ResponsibilityItem {
  title: string
  desc: string
}

export interface PdfReportData {
  certificationName: string
  certificationCode: string
  accentColorRgb: [number, number, number]
  responsibilities: ResponsibilityItem[]
  locale: 'es' | 'en'
}

export function generateResponsibilitiesPDF(data: PdfReportData) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const pw = doc.internal.pageSize.getWidth()
  const ph = doc.internal.pageSize.getHeight()
  const ml = 16
  const mr = 16
  const cw = pw - ml - mr
  let y = 0

  const [r, g, b] = data.accentColorRgb

  // ── Header bar ─────────────────────────────────────────────
  doc.setFillColor(r, g, b)
  doc.rect(0, 0, pw, 28, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(255, 255, 255)
  doc.text('AECOMI', ml, 12)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(data.certificationName, ml, 20)

  // Badge right side
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(data.certificationCode, pw - mr - doc.getTextWidth(data.certificationCode), 18)

  y = 38

  // ── Title ───────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.setTextColor(30, 30, 30)
  const heading = data.locale === 'en' ? 'Main Responsibilities' : 'Responsabilidades Principales'
  doc.text(heading, ml, y)
  y += 3

  doc.setDrawColor(r, g, b)
  doc.setLineWidth(0.5)
  doc.line(ml, y, pw - mr, y)
  y += 8

  // ── Responsibilities ────────────────────────────────────────
  data.responsibilities.forEach((item, idx) => {
    // New page guard (title + at least one line of desc)
    if (y > ph - 30) {
      doc.addPage()
      y = 16
    }

    // Number bubble
    doc.setFillColor(r, g, b)
    doc.circle(ml + 4, y - 1, 4, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(255, 255, 255)
    const numStr = String(idx + 1)
    doc.text(numStr, ml + 4 - doc.getTextWidth(numStr) / 2, y + 1)

    // Title
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.setTextColor(r, g, b)
    const titleX = ml + 11
    const titleLines = doc.splitTextToSize(item.title, cw - 11)
    doc.text(titleLines, titleX, y)
    y += titleLines.length * 5 + 1

    // Description
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(60, 60, 60)
    const descLines: string[] = doc.splitTextToSize(item.desc, cw - 5)
    descLines.forEach((line: string) => {
      if (y > ph - 22) {
        doc.addPage()
        y = 16
      }
      doc.text(line, ml + 5, y)
      y += 4.5
    })

    y += 4
  })

  // ── Footer on every page ────────────────────────────────────
  const totalPages: number = (doc.internal as any).getNumberOfPages()
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p)
    doc.setFillColor(240, 240, 240)
    doc.rect(0, ph - 10, pw, 10, 'F')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(120, 120, 120)
    const dateStr = new Date().toLocaleDateString(data.locale === 'en' ? 'en-GB' : 'es-ES')
    const footerLeft = data.locale === 'en'
      ? `Generated by AECOMI · ${dateStr}`
      : `Generado por AECOMI · ${dateStr}`
    doc.text(footerLeft, ml, ph - 4)
    doc.text(`${p} / ${totalPages}`, pw - mr - 10, ph - 4)
  }

  doc.save(`${data.certificationCode}_Responsabilidades.pdf`)
}
